[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración de compresión
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Encoding = "gzip"

# Redirecciones y configuración de dominio
[[redirects]]
  from = "http://gusi.dev/*"
  to = "https://gusi.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.gusi.dev/*"
  to = "https://gusi.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gusi.dev/*"
  to = "https://gusi.dev/:splat"
  status = 301
  force = true